### ISSUE TITLE
Composer require failed ?

### ISSUE THREAD

**Issue by Rayzen-dev** [llaville/umlwriter#22]
# Bug report category

- [x] Installation issue.
- [ ] Feature issue.
- [ ] Other. Please specify in `Summary` section

## Summary
Can't install with composer

## Installation issue.
My env:
- PHP 8.0.19
- Symfony 5.3

My package.json
```yml
{
    "require": {
        "php": ">=7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ezyang/htmlpurifier": "^4.13",
        "mailjet/mailjet-apiv3-php": "^1.5",
        "symfony/apache-pack": "^1.0",
        "symfony/asset": "5.3.*",
        "symfony/console": "5.3.*",
        "symfony/debug-bundle": "5.3.*",
        "symfony/dotenv": "5.3.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "5.3.*",
        "symfony/framework-bundle": "5.3.*",
        "symfony/runtime": "5.3.*",
        "symfony/translation": "5.3.*",
        "symfony/twig-bundle": "5.3.*",
        "symfony/validator": "5.3.*",
        "symfony/yaml": "5.3.*",
        "twig/twig": "^3.3"
    },
    "require-dev": {
        "symfony/stopwatch": "5.3.*",
        "symfony/var-dumper": "5.3.*",
        "symfony/web-profiler-bundle": "5.3.*"
    }
}
```

I try to run `composer require bartlett/umlwriter ^3.0` and get:
```
$ composer require bartlett/umlwriter ^3.0
// ...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bartlett/umlwriter 3.0 -> satisfiable by bartlett/umlwriter[3.0.0].
    - bartlett/umlwriter 3.0.0 requires graphp/graph dev-master as 1.0.0 -> found graphp/graph[dev-master] but it does not match your minimum-stability.
```
